### ISSUE TITLE
Websocket URL is invalid

### ISSUE THREAD

**Issue by theAbdoSabbagh** [TheonlyIcebear/Bloxflip.py#1]
It returns the error
```py
websocket._exceptions.WebSocketAddressException: [Errno -2] Name or service not known
```
when trying to connect, and yes my auth is valid. The new WS URL is:

`wss://ws.bloxflip.com/socket.io/?EIO=3&transport=websocket`

However I've failed to make a working websocket connection with that URL as it always returns the error
```py
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by TheonlyIcebear** [comment]
I've updated this in the newest release now
