### ISSUE TITLE
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden

### ISSUE THREAD

**Issue by Imdaros** [TheonlyIcebear/Bloxflip.py#3]
Always getting this error; 

`websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden`

My auth token is a valid token.

**Comment by TheonlyIcebear** [comment]
I can't really solve this as bloxflip is currently blocking websocket connections I recommend just waiting
